
  # ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dotnetVersion: 2.2.300
  version: '0.1.0-preview-$(Build.BuildNumber)'

steps:

- task: DotNetCoreInstaller@0
  displayName: 'install dotnet sdk version $(dotnetVersion)'
  inputs:
    version: $(dotnetVersion) # replace this value with the version that you need for your project
  
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test /p:AltCover=true /p:AltCoverXmlReport="..\coverage.xml"
  displayName: 'dotnet test $(buildConfiguration) with code coverage'
  
- task: reportgenerator@4
  inputs:
    reports: 'coverage.xml'
    targetdir: 'reports'
  displayName: generate reports

- script: dotnet pack -o $(Build.ArtifactStagingDirectory) --no-dependencies --no-build --include-symbols -p:PackageVersion=$(version) 
  displayName: 'dotnet pack version $(version)'

- script: dotnet nuget push $(Build.ArtifactStagingDirectory)/ -s $(feedUrl) -k $(apikey)
  displayName: push to myget